# Generated by Django 3.2.9 on 2022-01-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20220129_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('pOrS', models.CharField(choices=[('P', 'Purchase'), ('S', 'Sales')], max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qtdP',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qtdS',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qtdStock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='revenues',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='productordem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
