# Generated by Django 3.2.9 on 2022-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
