# Generated by Django 3.2.9 on 2022-01-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sell',
        ),
    ]
