# Generated by Django 3.2.9 on 2022-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_delete_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('purchase', models.FloatField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('qtdStock', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('revenues', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
