# Generated by Django 3.2.9 on 2022-01-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_movement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
