# Generated by Django 3.2.9 on 2022-01-28 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='qtdPurch',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='qtdSell',
        ),
    ]
