# Generated by Django 3.2.9 on 2022-01-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220128_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='qtdP',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='qtdS',
        ),
        migrations.AddField(
            model_name='product',
            name='qtdP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qtdS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='qtd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sell',
            name='qtd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
