# Generated by Django 3.2.9 on 2022-01-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_sell_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('productId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('purchase', models.FloatField(blank=True, null=True)),
                ('sales', models.FloatField(blank=True, null=True)),
                ('qtdStock', models.FloatField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('revenues', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
